import { StyleSheet } from 'react-native'
import { colors, radius, shadow, spacing } from '../theme/theme'

export const styles = StyleSheet.create({
  container: {
    padding: spacing.lg,
    paddingBottom: spacing.xl,
  },
  heading: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '900',
  },
  copy: {
    color: colors.mutedText,
    fontSize: 14,
    marginTop: spacing.xs,
    marginBottom: spacing.lg,
  },
  filters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  filterChip: {
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  filterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterText: {
    color: colors.mutedText,
    fontWeight: '800',
    fontSize: 12,
  },
  filterTextActive: {
    color: colors.deepGreen,
  },
  error: {
    color: colors.danger,
    backgroundColor: colors.dangerSoft,
    borderRadius: radius.sm,
    padding: spacing.md,
    marginBottom: spacing.md,
    fontWeight: '700',
  },
  emptyCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.xl,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '900',
    marginTop: spacing.md,
  },
  emptyText: {
    color: colors.mutedText,
    marginTop: spacing.xs,
  },
  list: {
    gap: spacing.md,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
  },
  cardTop: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  main: {
    flex: 1,
  },
  title: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
  },
  meta: {
    color: colors.mutedText,
    fontSize: 12,
    marginTop: 3,
  },
  route: {
    color: colors.green,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 5,
  },
  amountBox: {
    alignItems: 'flex-end',
  },
  amount: {
    color: colors.text,
    fontWeight: '900',
  },
  badge: {
    color: colors.deepGreen,
    backgroundColor: colors.primarySoft,
    borderRadius: radius.pill,
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: 4,
    marginTop: spacing.sm,
    fontSize: 12,
    fontWeight: '800',
  },
  dateLine: {
    color: colors.green,
    fontSize: 12,
    marginTop: spacing.md,
  },
  actions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  secondaryButton: {
    flex: 1,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.primary,
    padding: spacing.md,
    alignItems: 'center',
  },
  secondaryText: {
    color: colors.deepGreen,
    fontWeight: '900',
  },
  detailBox: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    marginTop: spacing.md,
    paddingTop: spacing.md,
  },
  infoLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  infoLabel: {
    color: colors.mutedText,
  },
  infoValue: {
    flex: 1,
    color: colors.text,
    fontWeight: '800',
    textAlign: 'right',
  },
  sectionSmall: {
    color: colors.green,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  expenseLine: {
    backgroundColor: colors.background,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  expenseTitle: {
    color: colors.text,
    fontWeight: '900',
  },
  amountSmall: {
    color: colors.deepGreen,
    fontWeight: '900',
    marginTop: spacing.xs,
  },
  justificatifs: {
    marginTop: spacing.sm,
    gap: spacing.sm,
  },
  justificatifCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.sm,
  },
  justificatifImage: {
    width: 58,
    height: 58,
    borderRadius: radius.sm,
    backgroundColor: colors.primarySoft,
  },
  justificatifFile: {
    width: 58,
    height: 58,
    borderRadius: radius.sm,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  justificatifInfo: {
    flex: 1,
  },
  justificatifTitle: {
    color: colors.text,
    fontWeight: '900',
  },
  justificatifLink: {
    color: colors.green,
    fontSize: 12,
    fontWeight: '900',
    marginTop: 3,
  },
  warning: {
    color: colors.warning,
    backgroundColor: colors.warningSoft,
    borderRadius: radius.sm,
    padding: spacing.md,
    marginTop: spacing.sm,
    fontWeight: '800',
  },
  rejectBox: {
    marginTop: spacing.md,
  },
  input: {
    minHeight: 48,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    color: colors.text,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.sm,
    fontSize: 14,
  },
  rejectConfirm: {
    borderRadius: radius.md,
    backgroundColor: colors.danger,
    padding: spacing.md,
    alignItems: 'center',
  },
  rejectConfirmText: {
    color: colors.surface,
    fontWeight: '900',
  },
  adminActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  approveButton: {
    flex: 1,
    borderRadius: radius.md,
    backgroundColor: colors.successSoft,
    padding: spacing.md,
    alignItems: 'center',
  },
  approveText: {
    color: colors.success,
    fontWeight: '900',
  },
  rejectButton: {
    flex: 1,
    borderRadius: radius.md,
    backgroundColor: colors.dangerSoft,
    padding: spacing.md,
    alignItems: 'center',
  },
  rejectText: {
    color: colors.danger,
    fontWeight: '900',
  },
  paidButton: {
    flex: 1,
    borderRadius: radius.md,
    backgroundColor: colors.blueSoft,
    padding: spacing.md,
    alignItems: 'center',
  },
  paidText: {
    color: colors.blue,
    fontWeight: '900',
  },
})
